# default: use dockerd's logging options, maybe json
x-logging-default: &logging_options {}

services:
  moeflow-mongodb:
    image: ${DH_DOMAIN}/mongo:4.4.1
    restart: unless-stopped
    volumes:
      - ./mongodb/data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASS}
    command: ['--quiet', '--setParameter', 'logLevel=0', '--wiredTigerCacheSizeGB', '0.25']
    logging: *logging_options
    healthcheck:
      test: ["CMD","bash", '-c', "exec 9<> /dev/tcp/127.0.0.1/27017"]
      interval: 15s
      timeout: 5s
      start_period: 10s

  moeflow-redis:
    image: ${DH_DOMAIN}/redis:7-alpine
    restart: unless-stopped
    command: ['redis-server', '--appendonly', 'yes', '--maxmemory', '256mb', '--maxmemory-policy', 'allkeys-lru']
    volumes:
      - ./redis:/data
    logging: *logging_options
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s

  moeflow-backend: &backend_base
    image: ghcr.io/umeabc/moeflow-backend:v1.1.8-iroha10-fix15
    command: gunicorn -t 120 -w 2 -b 0.0.0.0:5000 "app:create_app()"
    volumes:
      - /data/stoarge/:/app/storage
      - ./logs/moeflow-backend:/app/logs
    env_file:
      - .env-backend
    environment:
      # forward envs set in .env
      # STORAGE_TYPE=R2 时改为 R2 公开域名，如 https://pub-<hash>.r2.dev/（见 .env-backend 注释）
      STORAGE_DOMAIN: http://${DOMAIN}/storage/
      MONGODB_URI: mongodb://${MONGODB_USER}:${MONGODB_PASS}@moeflow-mongodb:27017/moeflow?authSource=admin
      CELERY_BROKER_URL: redis://moeflow-redis:6379/0
      MAX_CONTENT_LENGTH_MB: ${MAX_CONTENT_LENGTH_MB}
    restart: unless-stopped
    logging: *logging_options
    depends_on:
      moeflow-backend-init:
        condition: service_completed_successfully

  moeflow-backend-init:
    <<: *backend_base
    command: python3 manage.py migrate
    restart: 'no'
    depends_on: &backend-deps
      moeflow-redis:
        condition: service_healthy
      moeflow-mongodb:
        condition: service_healthy

  moeflow-celery:
    <<: *backend_base
    command: celery --app app.celery worker --queues default,output --hostname celery.default --loglevel=info

  moeflow-frontend:
    image: ghcr.io/umeabc/moeflow-frontend:v1.1.7-iroha10-fix3
    restart: unless-stopped
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/certificates:/certificates
      - /data/stoarge/:/storage
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    environment:
      DOMAIN: ${DOMAIN}
      MAX_CONTENT_LENGTH_MB: ${MAX_CONTENT_LENGTH_MB}
    links: [moeflow-backend]
    logging: *logging_options
